Repository orange-cloudavenue/terraform-plugin-framework-validators, pull requests merged in 2025-01, with the labels that each got.

#19 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/push_main.yml
Labels: Chore, size/XS, sync

#21 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/push_main.yml
Labels: Chore, size/XS, sync

#20 chore: synced file(s) with orange-cloudavenue/orange-cloudavenue.github.io
  docs/stylesheets/orange.css
Labels: Chore, size/S, sync

#22 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/push_main.yml
Labels: Chore, size/XS, sync

#23 docs: update documentation portal
  docs/boolvalidator/index.md
  docs/boolvalidator/not.md
  docs/common/null_if_attribute_is_one_of.md
  docs/common/null_if_attribute_is_set.md
  docs/common/oneofwithdescriptionifattributeisoneof.md
  docs/common/require_if_attribute_is_one_of.md
  docs/common/require_if_attribute_is_set.md
  docs/getting-started.md
  docs/index.md
  docs/int64validator/attribute_is_divisible_by_an_integer.md
  docs/int64validator/index.md
  docs/int64validator/not.md
  docs/int64validator/oneofwithdescription.md
  docs/int64validator/zero_remainder.md
  docs/listvalidator/index.md
  docs/listvalidator/not.md
  docs/mapvalidator/index.md
  docs/mapvalidator/not.md
  docs/setvalidator/index.md
  docs/setvalidator/not.md
  docs/stringvalidator/index.md
  docs/stringvalidator/isip.md
  docs/stringvalidator/ismacaddress.md
  docs/stringvalidator/isnetmask.md
  docs/stringvalidator/isnetwork.md
  docs/stringvalidator/isurn.md
  docs/stringvalidator/isuuid.md
  docs/stringvalidator/not.md
  docs/stringvalidator/oneofwithdescription.md
  docs/stringvalidator/prefixcontains.md
  mkdocs.yml
Labels: documentation, size/XS

#24 chore: synced file(s) with orange-cloudavenue/workflows
  .github/labels.yml
  .github/workflows/labeler.yml
  .github/workflows/pr.yml
  .github/workflows/pr_open.yml
Labels: Chore, sync, size/M

#25 chore: synced file(s) with orange-cloudavenue/workflows
  .github/labels.yml
Labels: size/XS, chore, sync

#26 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/release.yml
  .github/workflows/release_created.yml
Labels: size/S, chore, sync

#28 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/pr.yml
Labels: size/XS, chore, sync

#17 feat: add objectvalidator with common validators
  .changelog/17.txt
  docs/index.md
  docs/objectvalidator/index.md
  docs/objectvalidator/not.md
  internal/not_valid.go
  mkdocs.yml
  objectvalidator/not_valid.go
  objectvalidator/not_valid_test.go
  objectvalidator/null_if_attribute_is_one_of.go
  objectvalidator/null_if_attribute_is_set.go
  objectvalidator/require_if_attribute_is_one_of.go
  objectvalidator/require_if_attribute_is_set.go
Labels: community

#29 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/pr.yml
  .github/workflows/pr_close.yml
Labels: sync

#30 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/pr.yml
  .licenserc.yaml
  LICENSE
Labels: size/S, chore, sync

#32 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/pr.yml
Labels: sync

#36 chore: synced file(s) with orange-cloudavenue/workflows
  .github/workflows/pr.yml
  .github/workflows/pr_close.yml
  .github/workflows/pr_open.yml
  .licenserc.yaml
Labels: size/S, chore, sync

#38 feat(stringvalidator): add cases validator
  .changelog/37.txt
  docs/stringvalidator/cases.md
  docs/stringvalidator/index.md
  docs/stringvalidator/isnetwork.md
  stringvalidator/cases.go
  stringvalidator/cases/disallow_lower.go
  stringvalidator/cases/disallow_lower_test.go
  stringvalidator/cases/disallow_number.go
  stringvalidator/cases/disallow_number_test.go
  stringvalidator/cases/disallow_space.go
  stringvalidator/cases/disallow_space_test.go
  stringvalidator/cases/disallow_upper.go
  stringvalidator/cases/disallow_upper_test.go
  stringvalidator/cases/types.go
  stringvalidator/cases/validators.go
  stringvalidator/cases_test.go
Labels: size/L, feature

#40 chore: synced file(s) with orange-cloudavenue/workflows
  .licenserc.yaml
Labels: size/XS, chore, sync

#42 feat(int32validator): onboard a new validator
  .changelog/42.txt
  docs/int32validator/attribute_is_divisible_by_an_integer.md
  docs/int32validator/index.md
  docs/int32validator/not.md
  docs/int32validator/oneofwithdescription.md
  docs/int32validator/zero_remainder.md
  int32validator/attribute_is_divisible_by_an_integer.go
  int32validator/attribute_is_divisible_by_an_integrer_test.go
  int32validator/not_valid.go
  int32validator/not_valid_test.go
  int32validator/null_if_attribute_is_one_of.go
  int32validator/null_if_attribute_is_set.go
  int32validator/one_of_with_description.go
  int32validator/one_of_with_description_if_attribute_is_one_of.go
  int32validator/one_of_with_description_test.go
  int32validator/require_if_attribute_is_one_of.go
  int32validator/require_if_attribute_is_set.go
  int32validator/zero_remainder.go
  int32validator/zero_remainder_test.go
  internal/not_valid.go
  internal/null_if_attribute_is_one_of.go
  internal/null_if_attribute_is_one_of_test.go
  internal/null_if_attribute_is_set.go
  internal/null_if_attribute_is_set_test.go
  internal/one_of_with_description.go
  internal/one_of_with_description_if_attribute_is_one_of.go
  internal/one_of_with_description_if_attribute_is_one_of_test.go
  internal/require_if_attribute_is_one_of.go
  internal/require_if_attribute_is_one_of_test.go
  internal/require_if_attribute_is_set.go
  internal/require_if_attribute_is_set_test.go
  mkdocs.yml
Labels: size/XL, feature

#43 chore: synced file(s) with orange-cloudavenue/workflows
  .github/labels.yml
  .github/pull-request-size.yml
  .github/workflows/labeler.yml
  .licenserc.yaml
Labels: size/S, chore, sync

#45 chore: synced file(s) with orange-cloudavenue/workflows
  .licenserc.yaml
  .pre-commit-config.yaml
Labels: size/S, chore, sync
